### ISSUE TITLE
spheres size stepping should be finer

### ISSUE THREAD

**Issue by xulman** [xulman/mastodon-sciview-take2#2]
the on-the-fly multiplicative factor applied to a sphere radius to decide radius (or scale?) of the Sphere node object can be changed at runtime with 'O' and 'shift+O' (O - ball gets small or Capital O with Shift gets larger), it is using too harsh/large step size

**Comment by smlpt** [comment]
This was fixed a while ago, can't remember in which PR.
Sphere scaling and line width scaling are fine grained enough now.
